# Generated by Django 2.1.7 on 2019-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.IntegerField(null=True),
        ),
    ]
