# Generated by Django 2.1.7 on 2019-03-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190322_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allows_sale',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
