# Generated by Django 2.1.7 on 2019-03-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_imageproduct_is_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
