# Generated by Django 2.1.7 on 2019-04-13 14:21

from django.db import migrations, models
import django_start.apps.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190324_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, default=django_start.apps.product.models.increment_product_code_number, max_length=20, null=True),
        ),
    ]
