# Generated by Django 2.1.7 on 2019-05-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetails',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='sub_total',
        ),
    ]
