# Generated by Django 2.1.7 on 2019-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=75)),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
