# Generated by Django 2.1.7 on 2019-04-10 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=75, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('tax_code', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('area', models.CharField(max_length=255, null=True)),
                ('wards', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateField(null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
