# Generated by Django 2.1.7 on 2019-04-13 14:21

from django.db import migrations, models
import django_start.apps.customer.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20190411_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, default=django_start.apps.customer.models.increment_customer_code_number, max_length=20, null=True),
        ),
    ]
