# Generated by Django 2.1.7 on 2019-04-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20190413_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_date',
            field=models.DateField(null=True),
        ),
    ]
