# Generated by Django 2.1.7 on 2019-02-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(default='2019-02-21', max_length=8),
            preserve_default=False,
        ),
    ]
