# Generated by Django 2.1.7 on 2019-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190228_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
