# Generated by Django 2.1.7 on 2019-03-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190302_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(default='1996-12-2'),
            preserve_default=False,
        ),
    ]
