# Generated by Django 2.1.7 on 2019-05-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190423_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountemployee',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Role'),
        ),
        migrations.DeleteModel(
            name='AccountEmployee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
